/*
 * Copyright 2026 the original author or authors
 *
 * SPDX-License-Identifier: MIT
 */

package net.nmoncho.sbt.osv
package settings

import sbt.Logger

/** Trait used to define how Summaries are generated after an analysis
  */
trait SummaryReport {

  /** Builds an analysis summary using the scanned dependencies and the failing CVSS Score
    *
    * @param dependencies  scanned dependencies
    * @param failCvssScore failing CVSS Score
    * @return
    */
  def buildSummary(
      analysisResult: Map[Dependency, Set[Vulnerability]],
      failCvssScore: Double
  ): String

}

object SummaryReport {

  private final val NewLine = System.getProperty("line.separator", "\n").intern()

  /** Shows the summary to the console
    *
    * @param name          project name
    * @param dependencies  scanned dependencies
    * @param failCvssScore failing CVSS Score
    * @param report        report type
    * @param log           logger
    */
  def showSummary(
      name: String,
      analysisResult: Map[Dependency, Set[Vulnerability]],
      failCvssScore: Double,
      report: SummaryReport
  )(
      implicit log: Logger
  ): Unit = {
    val summary = report.buildSummary(analysisResult, failCvssScore)

    log.warn(
      s"\n\nOne or more dependencies were identified with known vulnerabilities in [$name]:\n\n${summary}" +
        "\n\nSee the OSV report for more details.\n\n"
    )
  }

  /** Processes a vulnerability to include in a report
    *
    * If it's a failing vulnerability, it will output the line in yellow.
    *
    * @param v vulnerability to report
    * @param failCvssScore failing score
    * @return vulnerability report line
    */
  private def processVulnerability(v: Vulnerability, failCvssScore: Double): String = {
    val score = v.scores.map(s => s"${s.name} ${s.score}").mkString("(", ", ", ")")

    if (failingVulnerability(v, failCvssScore)) {
      s"${scala.Console.YELLOW}${v.id}${scala.Console.RESET} ${scala.Console.YELLOW}${score})${scala.Console.RESET}"
    } else {
      s"${v.id} ${score}"
    }
  }

  /** Processes dependencies to be included in the report
    *
    * @param dependencies        scanned dependencies
    * @param reportVulnerability predicate to define if a [[Vulnerability]] should be shown or not in the summary
    * @param summary             [[StringBuilder]] used for aggregating the report
    */
  private def dependencyProcessor(
      analysisResult: Map[Dependency, Set[Vulnerability]],
      reportVulnerability: (Vulnerability, Double) => Boolean,
      failCvssScore: Double,
      summary: StringBuilder
  ): Unit =
    analysisResult.foreach { case (dependency, vulnerabilities) =>
      if (vulnerabilities.nonEmpty) {
        // TODO sort vulnerability by score in descending order so most critical are first

        val formattedVulnerabilities = vulnerabilities.collect {
          case v if reportVulnerability(v, failCvssScore) =>
            processVulnerability(v, failCvssScore)
        }

        if (formattedVulnerabilities.nonEmpty) {
          summary
            .append(dependency.file.getName)
            .append(": ")

          summary.append(
            formattedVulnerabilities.mkString(", ")
          )

          summary.append(NewLine)
        }
      }
    }

  /** Summary generated by Owasp DependencyCheck
    */
  object DependencyCheck extends SummaryReport {

    override def buildSummary(
        analysisResult: Map[Dependency, Set[Vulnerability]],
        failCvssScore: Double
    ): String = {
      val summary = new StringBuilder

      analysisResult.foreach { case (dependency, vulnerabilities) =>
        val ids = vulnerabilities.map(_.id).mkString(", ")

        if (ids.nonEmpty) {
          summary
            .append(dependency.coordinates)
            .append(" (")
            .append(dependency.file.getName)
            .append("): ")
            .append(ids)
            .append(NewLine)
        }
      }

      summary.toString()
    }

  }

  /** Shows all vulnerabilities in the summary with their corresponding score, whether they are an
    * offending vulnerability or not.
    */
  object AllVulnerabilities extends SummaryReport {

    override def buildSummary(
        analysisResult: Map[Dependency, Set[Vulnerability]],
        failCvssScore: Double
    ): String = {
      val summary = new StringBuilder

      dependencyProcessor(analysisResult, (_, _) => true, failCvssScore, summary)

      summary.toString()
    }

  }

  /** Shows only offending vulnerabilities in the summary with their corresponding score.
    */
  object OffendingVulnerabilities extends SummaryReport {

    override def buildSummary(
        analysisResult: Map[Dependency, Set[Vulnerability]],
        failCvssScore: Double
    ): String = {
      val summary = new StringBuilder

      dependencyProcessor(
        analysisResult,
        failingVulnerability,
        failCvssScore,
        summary
      )

      summary.toString()
    }

  }

}
